name: Test Push
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Import GPG secret key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          make all
          curl -#Lkf \
            -o /home/runner/spring-startup-analyzer/spring-boot-demo.jar \
            https://github.com/linyimin0812/spring-startup-analyzer/releases/download/v2.0.0/spring-boot-demo.jar
          ls -lrt

      - uses: actions/upload-artifact@v3
        with:
          name: spring-startup-analyzer
          path: /home/runner/spring-startup-analyzer/
          if-no-files-found: error

  test-mac:
    runs-on: macos-12
    needs: [build]
    steps:
      # 安装 Liberica JDK 11
      - uses: actions/setup-java@v3
        with:
          distribution: "liberica"
          java-version: "11"

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: spring-startup-analyzer
          path: /Users/runner/

      - name: Execute spring-boot-demo.jar
        run: |
          ls -lrt
          mkdir -p ./spring-startup-analyzer/output
          tar -zxvf spring-startup-analyzer.tar.gz -C ./spring-startup-analyzer
          nohup java -javaagent:/Users/runner/spring-startup-analyzer/lib/spring-profiler-agent.jar \
            -Dproject.name=demo-mac \
            -Dspring-startup-analyzer.admin.http.server.port=8066 \
            -jar /Users/runner/spring-boot-demo.jar &
                    
          sleep 60
          file_count=$(ls -al /Users/runner/spring-startup-analyzer/output/ | grep -c "mac-demo")
          if [ "$file_count" -eq 2 ]; then
            echo "mac-test success"
            exit 0
          fi
          exit 1
        working-directory: /Users/runner/
